fail_fast: false
repos:
  - repo: https://github.com/HaoXianSen/Objective-CLint.git
    rev: v1.0.0
    hooks:
      - id: objc-lint
        name: objc-format
        entry: bin/format-objc-hook --reporter open_html
        language: script
        require_serial: true
        verbose: true
