fail_fast: false
repos:
  - repo: https://github.com/HaoXianSen/Objective-CLint.git
    rev: v0.0.5
    hooks:
      - id: objc-lint
        name: objc-format
        language: script
        require_serial: true
        verbose: true
